[package]
name = "openzwave-stateful"
version = "0.1.0"
authors = ["Julien Wajsberg <felash@gmail.com>"]

[dependencies]
"openzwave" = { git = "https://github.com/fxbox/openzwave-rust", branch = "demo-2016-04-19" }

